package redis

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/llm-d/llm-d-async/api"
	"github.com/llm-d/llm-d-async/pipeline"
	"github.com/redis/go-redis/v9"
)

var _ pipeline.Gate = (*PolicyVersionGate)(nil)

const (
	// DefaultPolicyVersionAttribute is the message metadata key naming the
	// policy version a request must be served by.
	DefaultPolicyVersionAttribute = "policy_version"
	// DefaultPolicyVersionKey is the Redis key holding the version currently
	// loaded by the inference backend.
	DefaultPolicyVersionKey = "policy:live_version"
	// TenantPlaceholder is the substring of a version key replaced with the
	// requesting tenant.
	TenantPlaceholder = "{tenant}"
)

// PolicyVersionGate admits a request only when the policy version it asks for
// is close enough to the version currently loaded by the backend, published out
// of band under a Redis key.
//
// Reinforcement-learning rollouts must be generated by a known policy version:
// an adapter swap in the middle of a batch silently mixes versions, and
// on-policy algorithms then compute wrong gradients rather than failing. The
// gate turns that into an explicit decision. A request that runs ahead of the
// backend parks until its version goes live; one that has fallen too far behind
// is dropped, because the trainer would discard it on arrival anyway.
//
// How far behind is too far is the caller's to say. Off-policy trainers sample
// and train concurrently and deliberately tolerate a bounded lag, so a gate that
// dropped every request a single version behind would discard work the trainer
// intended to use; maxLag exists to be set to the trainer's own tolerance.
//
// The parking verdict only takes effect for a worker-pool gate: the queue-side
// dequeue paths act on Refuse and Drop but dispatch on Wait.
type PolicyVersionGate struct {
	rdb             *redis.Client
	attribute       string
	versionKey      string
	tenantAttribute string
	maxLag          int64
}

// NewPolicyVersionGate builds a gate reading the requested version from the
// named message attribute, metadata first and forwarded headers second, and the
// live version from versionKey.
//
// maxLag is how many versions behind live a request may be and still be
// admitted; zero admits only the live version.
//
// A versionKey containing TenantPlaceholder is resolved per request, reading the
// tenant from tenantAttribute the same way; see versionKeyFor.
//
// Both attributes are matched against header names verbatim, so a coordinator
// forwarding either must list it under exactly this string.
func NewPolicyVersionGate(client *redis.Client, attribute, versionKey, tenantAttribute string, maxLag int64) *PolicyVersionGate {
	return &PolicyVersionGate{
		rdb:             client,
		attribute:       attribute,
		versionKey:      versionKey,
		tenantAttribute: tenantAttribute,
		maxLag:          maxLag,
	}
}

// Budget implements pipeline.Gate. The gate expresses correctness rather than
// capacity, so it never narrows the dispatch budget.
func (g *PolicyVersionGate) Budget(ctx context.Context) float64 {
	return 1.0
}

// Apply implements pipeline.Gate.
func (g *PolicyVersionGate) Apply(ctx context.Context, msg *api.InternalRequest, releases *[]pipeline.GateReleaseFunc) (pipeline.Verdict, error) {
	want := g.requestedVersion(msg)
	if want == "" {
		// Requests that name no version are not version-coupled.
		return pipeline.Continue(), nil
	}

	key := g.versionKeyFor(msg)
	if key == "" {
		// Per-tenant key with no tenant on the request: there is no published
		// version this request can be measured against.
		return pipeline.Continue(), nil
	}

	live, err := g.rdb.Get(ctx, key).Result()
	if errors.Is(err, redis.Nil) {
		// Nothing has been published yet; there is no version to disagree with.
		return pipeline.Continue(), nil
	}
	if err != nil {
		// Fail open, matching the quota gate: a Redis outage must not stall
		// every worker in the pool.
		return pipeline.Continue(), fmt.Errorf("failed to read live policy version %q: %w", key, err)
	}

	if want == live {
		return pipeline.Continue(), nil
	}

	lag, ordered := versionLag(want, live)
	switch {
	case !ordered:
		// Not comparable, so not provably obsolete. Park rather than discard.
		return pipeline.Wait(), nil
	case lag > g.maxLag:
		result := api.NewErrorResult(msg.PublicRequest, msg.InternalRouting, api.ErrCodeGateDropped,
			fmt.Sprintf("policy version %s is stale, live version is %s", want, live))
		return pipeline.Drop(&result), nil
	case lag > 0:
		// Behind, but inside the tolerance the caller declared.
		return pipeline.Continue(), nil
	default:
		// Ahead of the backend. Park until the version goes live; the worker's
		// deadline bounds the wait.
		return pipeline.Wait(), nil
	}
}

// requestedVersion reads the wanted version off the request.
func (g *PolicyVersionGate) requestedVersion(msg *api.InternalRequest) string {
	return g.lookup(msg, g.attribute)
}

// versionKeyFor resolves the Redis key holding the live version for this
// request.
//
// A key naming no tenant is shared by every request, which is right for a single
// training job and wrong for several: each publishes its own snapshot counter to
// the one key, so they overwrite each other and whichever job sits on the lower
// counter has every rollout dropped as stale. Templating the key per tenant
// gives each job its own version namespace on a shared pool.
//
// A templated key resolves to nothing, rather than to a literal placeholder,
// when the request names no tenant. Substituting nothing would silently point
// every such request at one key and reintroduce exactly the collision the
// template exists to avoid.
func (g *PolicyVersionGate) versionKeyFor(msg *api.InternalRequest) string {
	if !strings.Contains(g.versionKey, TenantPlaceholder) {
		return g.versionKey
	}
	tenant := g.lookup(msg, g.tenantAttribute)
	if tenant == "" {
		return ""
	}
	return strings.ReplaceAll(g.versionKey, TenantPlaceholder, tenant)
}

// lookup reads a named attribute from message metadata, falling back to the
// forwarded HTTP headers.
//
// The fallback is what makes the gate usable behind an unmodified coordinator.
// The async-broker fills Metadata with exactly two hardcoded entries, the quota
// attribute and traceparent; its one configurable header allowlist,
// forward_headers, lands in Headers instead. Reading only Metadata would
// therefore require patching the coordinator to carry these values, so the gate
// reads both. Metadata wins when set, which keeps a producer that submits to the
// queue directly, where Metadata is the natural field, from being overridden by
// a stray header.
func (g *PolicyVersionGate) lookup(msg *api.InternalRequest, name string) string {
	if name == "" {
		return ""
	}
	if v := msg.PublicRequest.ReqMetadata()[name]; v != "" {
		return v
	}
	return msg.PublicRequest.ReqHeaders()[name]
}

// versionLag reports how many versions want sits behind live, negative when it
// runs ahead. Versions are compared numerically; a pair that does not parse is
// reported as unordered, so the caller can park instead of discarding work it
// cannot prove is obsolete.
func versionLag(want, live string) (int64, bool) {
	wantN, err := strconv.ParseInt(want, 10, 64)
	if err != nil {
		return 0, false
	}
	liveN, err := strconv.ParseInt(live, 10, 64)
	if err != nil {
		return 0, false
	}
	return liveN - wantN, true
}
