package redis

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/llm-d/llm-d-async/api"
	"github.com/llm-d/llm-d-async/pipeline"
	"github.com/redis/go-redis/v9"
)

var _ pipeline.Gate = (*PolicyVersionGate)(nil)

const (
	// DefaultPolicyVersionAttribute is the message metadata key naming the
	// policy version a request must be served by.
	DefaultPolicyVersionAttribute = "policy_version"
	// DefaultPolicyVersionKey is the Redis key holding the version currently
	// loaded by the inference backend.
	DefaultPolicyVersionKey = "policy:live_version"
)

// PolicyVersionGate admits a request only when the policy version it asks for
// matches the version currently loaded by the backend, published out of band
// under a Redis key.
//
// Reinforcement-learning rollouts must be generated by a known policy version:
// an adapter swap in the middle of a batch silently mixes versions, and
// on-policy algorithms then compute wrong gradients rather than failing. The
// gate turns that into an explicit decision. A request that runs ahead of the
// backend parks until its version goes live; one that has fallen behind is
// dropped, because the trainer would discard it on arrival anyway.
//
// The parking verdict only takes effect for a worker-pool gate: the queue-side
// dequeue paths act on Refuse and Drop but dispatch on Wait.
type PolicyVersionGate struct {
	rdb        *redis.Client
	attribute  string
	versionKey string
}

// NewPolicyVersionGate builds a gate reading the requested version from the
// named message attribute, metadata first and forwarded headers second, and the
// live version from versionKey.
//
// attribute is matched against the header name verbatim, so a coordinator
// forwarding the version must list it under exactly this string.
func NewPolicyVersionGate(client *redis.Client, attribute, versionKey string) *PolicyVersionGate {
	return &PolicyVersionGate{
		rdb:        client,
		attribute:  attribute,
		versionKey: versionKey,
	}
}

// Budget implements pipeline.Gate. The gate expresses correctness rather than
// capacity, so it never narrows the dispatch budget.
func (g *PolicyVersionGate) Budget(ctx context.Context) float64 {
	return 1.0
}

// Apply implements pipeline.Gate.
func (g *PolicyVersionGate) Apply(ctx context.Context, msg *api.InternalRequest, releases *[]pipeline.GateReleaseFunc) (pipeline.Verdict, error) {
	want := g.requestedVersion(msg)
	if want == "" {
		// Requests that name no version are not version-coupled.
		return pipeline.Continue(), nil
	}

	live, err := g.rdb.Get(ctx, g.versionKey).Result()
	if errors.Is(err, redis.Nil) {
		// Nothing has been published yet; there is no version to disagree with.
		return pipeline.Continue(), nil
	}
	if err != nil {
		// Fail open, matching the quota gate: a Redis outage must not stall
		// every worker in the pool.
		return pipeline.Continue(), fmt.Errorf("failed to read live policy version %q: %w", g.versionKey, err)
	}

	if want == live {
		return pipeline.Continue(), nil
	}

	if g.isStale(want, live) {
		result := api.NewErrorResult(msg.PublicRequest, msg.InternalRouting, api.ErrCodeGateDropped,
			fmt.Sprintf("policy version %s is stale, live version is %s", want, live))
		return pipeline.Drop(&result), nil
	}

	// The requested version is ahead of the backend, or the two are not
	// ordered. Park until the backend catches up; the worker's deadline bounds
	// the wait.
	return pipeline.Wait(), nil
}

// requestedVersion reads the wanted version from message metadata, falling back
// to the forwarded HTTP headers.
//
// The fallback is what makes the gate usable behind an unmodified coordinator.
// The async-broker fills Metadata with exactly two hardcoded entries, the quota
// attribute and traceparent; its one configurable header allowlist,
// forward_headers, lands in Headers instead. Reading only Metadata would
// therefore require patching the coordinator to carry this one value, so the
// gate reads both. Metadata wins when set, which keeps a producer that submits
// to the queue directly, where Metadata is the natural field, from being
// overridden by a stray header.
func (g *PolicyVersionGate) requestedVersion(msg *api.InternalRequest) string {
	if v := msg.PublicRequest.ReqMetadata()[g.attribute]; v != "" {
		return v
	}
	return msg.PublicRequest.ReqHeaders()[g.attribute]
}

// isStale reports whether want has been superseded by live. Versions are
// compared numerically; a pair that does not parse is treated as unordered, so
// the caller parks instead of discarding work it cannot prove is obsolete.
func (g *PolicyVersionGate) isStale(want, live string) bool {
	wantN, err := strconv.ParseInt(want, 10, 64)
	if err != nil {
		return false
	}
	liveN, err := strconv.ParseInt(live, 10, 64)
	if err != nil {
		return false
	}
	return wantN < liveN
}
